08-10 19:48:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST" already exists; SQL statement:
CREATE TABLE TEST(NAME VARCHAR) [42101-176]
08-10 20:10:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
insert into test values('fisher') [90002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.Prepared.query(Prepared.java:213)
	at org.h2.command.CommandContainer.query(CommandContainer.java:91)
	at org.h2.command.Command.executeQuery(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:81)
	at com.fisher.db.H2Manager.execute(H2Manager.java:90)
	at com.fisher.db.H2Manager.main(H2Manager.java:40)
08-10 20:10:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
08-10 20:54:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ID"; expected "INSERT, {"; SQL statement:
ID [42001-176]
08-10 21:01:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE USERINFO ADD COLUMN PRIMARY[*] KEY (ID) "; expected "identifier"; SQL statement:
alter table userinfo add column PRIMARY KEY (id) [42001-176]
08-10 21:01:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE USERINFO ADD COLUMN PRIMARY[*] KEY ('id') "; expected "identifier"; SQL statement:
alter table userinfo add column PRIMARY KEY ('id') [42001-176]
08-10 21:04:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE USERINF(
ID VARCHAR(15) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
NOTE VARCHAR(100) NOT NULL,
PRIMARY KEY ('id'[*]) 
) "; expected "identifier"; SQL statement:
create table userinf(
id varchar(15) not null auto_increment,
username varchar(50) not null,
password varchar(50) not null,
note varchar(100) not null,
PRIMARY KEY ('id') 
) [42001-176]
08-10 21:04:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE USERINF(
ID VARCHAR(15) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
NOTE VARCHAR(100) NOT NULL,
PRIMARY KEY ('id'[*]) ,
) "; expected "identifier"; SQL statement:
create table userinf(
id varchar(15) not null auto_increment,
username varchar(50) not null,
password varchar(50) not null,
note varchar(100) not null,
PRIMARY KEY ('id') ,
) [42001-176]
08-10 21:05:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERINFO" not found; SQL statement:
alter table userinfo modify note varchar(100) [42102-176]
08-10 21:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USERINFO" not found; SQL statement:
alter table userinfo modify column note varchar(100) [42102-176]
08-10 21:06:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE USERINFO(
ID VARCHAR(15) NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
NOTE VARCHAR(100) ,
PRIMARY KEY ('id'[*]) 
) "; expected "identifier"; SQL statement:
create table userinfo(
id varchar(15) not null auto_increment,
username varchar(50) not null,
password varchar(50) not null,
note varchar(100) ,
PRIMARY KEY ('id') 
) [42001-176]
08-10 21:41:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "name" not found [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3122)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3210)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:304)
	at com.fisher.db.H2Manager.main(H2Manager.java:34)
2015-08-20 10:06:17 database: wrong user or password; user: "FISHER"
org.h2.message.DbException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:955)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2015-08-20 10:06:44 database: wrong user or password; user: "FISHER"
org.h2.message.DbException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.test(WebApp.java:893)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2015-08-20 10:07:35 database: wrong user or password; user: "FISHER"
org.h2.message.DbException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:955)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2015-08-20 10:09:39 database: wrong user or password; user: "FISHER"
org.h2.message.DbException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.test(WebApp.java:893)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2015-08-20 10:47:52 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "TITLE" not found; SQL statement:
insert into AdInfo(title ,latitude , longitude ,description ,imgUrl,rate ,rateNum ,sellPrice ,sellNum,tag,adUrl ) values('美味烧烤','39.821727','116.291672','最好吃，最有特殊餐厅','http://localhost:8080/HTTP/pic/listview_1.png','9','345','50','4030','好吃 实惠 量大','') [42122-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:648)
	at org.h2.command.Parser.parseColumn(Parser.java:855)
	at org.h2.command.Parser.parseColumnList(Parser.java:839)
	at org.h2.command.Parser.parseInsert(Parser.java:1039)
	at org.h2.command.Parser.parsePrepared(Parser.java:400)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1388)
	at org.h2.server.web.WebApp.query(WebApp.java:1061)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1023)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1010)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2015-08-20 14:31:37 database: wrong user or password; user: "FISHER"
org.h2.message.DbException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:106)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.test(WebApp.java:893)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2015-08-26 14:19:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP[*]（5）* FROM CONTENT "; SQL statement:
SELECT top（5）* FROM CONTENT [42000-188]
2015-08-26 14:25:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT ORDER BY ID DES[*] "; SQL statement:
SELECT top 5 * FROM CONTENT order by id des [42000-188]
2015-08-26 14:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT ORDER BY ID INC[*] "; SQL statement:
SELECT top 5 * FROM CONTENT order by id inc [42000-188]
2015-08-26 14:25:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT ORDER BY ID INS[*] "; SQL statement:
SELECT top 5 * FROM CONTENT order by id ins [42000-188]
2015-08-26 14:26:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT ORDER BY ID INS[*] "; SQL statement:
SELECT top 5 * FROM CONTENT order by id ins [42000-188]
2015-08-26 14:29:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT ORDER BY ID DES[*] "; SQL statement:
SELECT top 5 * FROM CONTENT order by id des [42000-188]
2015-08-26 14:37:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP 5 * FROM CONTENT WHERE ID IN ( SELECT TOP 15 ID FROM CONTENT DESC) ASC[*] "; SQL statement:
select top 5 * from content where id in ( select top 15 id from content desc) asc [42000-188]
